### ISSUE TITLE
Question About Mobile Dev

### ISSUE THREAD

**Issue by primesoftware** [KTXSoftware/Kha#171]
Is mobile dev working / ready? I read a KTX blog post that Android support is mostly broken? What about iOS? It was an old post from July, so I was curious if the latest github version fixed all that.

**Comment by RobDangerous** [comment]
iOS is very stable, two iOS games were released recently by Lubos.
Android is also back in working state since about a month (see the more recent blog post) but is currently seeing a lot of changes (helping Lubos to get the same two games on Android and Windows Mobile aka making everything super stable in all situations).
