### ISSUE TITLE
Option in khafile.js to set the width/height of the html canvas

### ISSUE THREAD

**Issue by RafaelOliveira** [KTXSoftware/Kha#201]
I'd like to see a option in khafile.js to set the width/height of the canvas in the html file. This way if I publish a project for others people to build I don't need to tell them what size the canvas should have, and I don't need to change the html file every time I need to recreate the project.

**Comment by wighawag** [comment]
I usually ignore the build/html5/index.html in my version control so that I can get it every time. khamake do not override it if already present.

On the other hand a while back I created a pull request to deal with this issue using a template system (https://github.com/KTXSoftware/khamake/pull/5) but I have been able to live without it so not sure if it is worth it.

**Comment by RobDangerous** [comment]
Fixed in KTXSoftware/khamake#30
