### ISSUE TITLE
What do you mean by Generational graphical/audio API design?

### ISSUE THREAD

**Issue by heretique** [KTXSoftware/Kha#401]
Hi,
I keep seeing one of the features of Kha being advertised as _**Generational graphical/audio API design**_. Can someone explain what that means and what are the advantages/disadvantages of such an architecture?

**Comment by RafaelOliveira** [comment]
For graphics this refer for the generations (and style) of graphics. 
g1: Only for pixels
g2: 2D graphics
g3: Old OpenGL / DirectX (not implemented yet)
g4: Modern OpenGL / Directx with shaders
g5: Vulkan / Metal (and I think DirectX 12)

And there is g2 in g4, that is 2D implemented in g4, and g4 in g5 (not implemented yet), that is g4 implemented in g5. As a example, html5 try to use g2 in g4 (2D implemented in WebGL), but if WebGL is not available it will fall back to canvas, that is just g2.

In g5 I think only Vulkan is implemented for now.
For audio I don't have experince to tell the details.

So Kha is made to cover everything you need to make games, you have access to shaders in both 2D (if available) and 3D, you can switch to OpenGL or DirectX with the same code, and each target/platform use a specific implementation (different from others Frameworks that uses SDL for everything), and its easy for Robert to port Kha for new platforms, because the code for each target is small.

**Comment by heretique** [comment]
Thanks Rafael, this makes it so much clear now.

**Comment by Disar** [comment]
To be more exact g3  = Fixed Function Pipeline. Basically no custom shaders and what not.

**Comment by RobDangerous** [comment]
The basic idea is that for every relevant "generational" change in how graphics/audio is used there is a fitting api which can be used on fitting hardware. Also earlier generations can be used on later generation platforms because there is always a (graphics/audio)n on (graphics/audio)n+1 implementation.

Buuuut... this is a bug tracker, for question please use the forum at http://forum.kode.tech
