### ISSUE TITLE
[BUG] ios building errors with drawing shapes

### ISSUE THREAD

**Issue by lewislepton** [KTXSoftware/Kha#417]
using the latest git kha version

building a simple application that just prints touchs & multi touch works fine. but when drawing a simple made block that would follow a finger on the x/y on screen does bring errors on trying to run it on a device.
does not make it past the build phase

<img width="263" alt="screen shot 2016-10-03 at 10 18 49" src="https://cloud.githubusercontent.com/assets/11299322/19032680/3609aa4c-8953-11e6-8f2b-e099cdb1a568.png">

**Comment by RobDangerous** [comment]
Can you get me the actual compiler output or upload a sample project?

**Comment by lewislepton** [comment]
[TOUCHINPUT.zip](https://github.com/KTXSoftware/Kha/files/506200/TOUCHINPUT.zip)

**Comment by RobDangerous** [comment]
Figured it out, but can't fix it, it's rather fancy. There is an internal header called Block.h inside Xcode/iOS. Having a Haxe class called Block creates another Block.h which is then included instead of Apple's Block.h and messes everything up. I can't seem to change Xcode/clang's include priorities and hxcpp uses global header paths - you could open an hxcpp issue to maybe get that changed. Meanwhile just rename your Block class.

**Comment by lewislepton** [comment]
hmm that is pretty fancy. cheers. will not name as Block in future ;)
