### ISSUE TITLE
[html5] Asm.js support

### ISSUE THREAD

**Issue by VcSaJen** [KTXSoftware/Kha#64]
[Feature request] Will be there any Asm.js support for html5 platform in the future?

**Comment by RobDangerous** [comment]
asm.js support is implemented (there is a C++/Emscripten backend), but I didn't add the option to khamake, because it doesn't seem very helpful. I didn't make any actual speed tests but I suspect it would slow a lot of Haxe code down. Haxe is a pretty good fit for plain JavaScript (it's garbage collected, always uses doubles,...).
