### ISSUE TITLE
no access to glViewPort functionality in g4

### ISSUE THREAD

**Issue by wighawag** [KTXSoftware/Kha#85]
There is currently no way to access glViewPort functionality

**Comment by wighawag** [comment]
I thought a bit about this and while I guess adding a viewport function should be possible on all target, I am not sure how to handle the g4.begin() call.
If we want to keep  the current behaviour the default, we need to pass a boolean parameter to set or not the viewport to the size of the framebuffer.
begin(resetViewPort:Bool =true)
what do you think?

**Comment by RobDangerous** [comment]
Well, the clear-color parameter in begin for comparison is really only there because on Android weird things happen when render targets are not cleared - so I wanted that to at least be the default behavior. Would similarly decide on a resetViewPort parameter depending on how exactly all the different targets behave.

**Comment by RobDangerous** [comment]
This has been fixed by a pull request from this very wighawag.
